### ISSUE TITLE
Incompatible with Essential Commands 

### ISSUE THREAD

**Issue by Tunga-Tech** [borisshoes/ArcanaNovum#11]
I've noticed that when using the /fly command with [Essential Commands](https://modrinth.com/mod/essential-commands) It will spam errors in the server console and not allow the player to fly.
`[Server thread]: [PlayerAbilityLib] Player ability minecraft:mayfly was updated externally (exp ected enabled, was disabled). java.lang.RuntimeException: stacktrace at knot/io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:63) ~[playerabilitylib-1.10 .0-23a75d3248fcb0d2.jar:?] at knot/io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71) ~[player abilitylib-1.10.0-23a75d3248fcb0d2.jar:?] at knot/net.minecraft.server.level.ServerPlayer.handler$dlf000$playerabilitylib$checkAbilityConsistency(ServerPl ayer.java:14703) ~[?:?] at knot/net.minecraft.server.level.ServerPlayer.onUpdateAbilities(ServerPlayer.java:1552) ~[?:?] at knot/net.borisshoes.arcananovum.callbacks.TickCallback.flightCheck(TickCallback.java:227) ~[arcananovum-3.0.5 %252B1.21.1.jar:?] at knot/net.borisshoes.arcananovum.callbacks.TickCallback.onTick(TickCallback.java:100) ~[arcananovum-3.0.5%252B 1.21.1.jar:?] at knot/net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43) ~[ fabric-lifecycle-events-v1-2.4.0+0f6c53cd19-c6aff05668ba7382.jar:?] at knot/net.minecraft.server.MinecraftServer.handler$blk000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer .java:5663) ~[server-intermediary.jar:?] at knot/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:940) ~[server-intermediary.jar:?] at knot/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697) ~[server-intermediary.jar:?] at knot/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:281) ~[server-intermediary.jar:? ] at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by borisshoes** [comment]
Thanks for the report! I will look into the issue. I will say that mod incompatibilities are somewhat low on my priority list, so it might be a while till I have a fix out for this.

**Comment by globalista-dev** [comment]
If I might add, Essential is not known for being a community and developer friendly mod. It's likely it's something on their side that broke Arcana Novum and they weren't (last time I checked) accepting PRs. I suggest that @Tunga-Tech use [e4mc](https://modrinth.com/mod/e4mc) or other open source options.

**Comment by borisshoes** [comment]
Fix is now live in 3.1.1
